#-------------------------------------------------------------------------------
# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening this issue. A contributor will be by to give feedback soon. In the meantime, please review the [Newcomers' Guide](https://docs.meshery.io/project/community#getting-involved-in-the-community) and sure to join the [community Slack](https://slack.meshery.io/).
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Yay, your first pull request! :thumbsup: A contributor will be by to give feedback soon. In the meantime, please review the [Newcomers' Guide](https://docs.meshery.io/project/community#getting-involved-in-the-community) and sure to join the [community Slack](https://slack.meshery.io/).

  Be sure to double-check that you have signed your commits. Here are instructions for [making signing an implicit activity while peforming a commit](https://docs.meshery.io/project/contributing#general-contribution-flow).

#-------------------------------------------------------------------------------
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Thanks for your contribution to the Meshery community! :tada:
   
  <picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/meshery/meshery.io/master/.github/welcome/Meshery-celebration-Dark.svg">
  <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/meshery/meshery.io/master/.github/welcome/Meshery-celebration-Light.svg">
  <img alt="Meshery Logo" src="">
  </picture>

  &nbsp; &#9; &nbsp; &#9;  &nbsp; &#9;  &nbsp; &#9; :star: Please leave a [star on the project](../stargazers). :smile:

#-------------------------------------------------------------------------------
# Configuration for request-info - https://github.com/behaviorbot/request-info
# Comment to reply with
requestInfoReplyComment: >
  Thanks for opening this issue. We welcome all input! If you could provide a little more information, this will greatly aide in its resolution. :thumbsup:
# *OPTIONAL* Add a list of people whose Issues/PRs will not be commented on
# keys must be GitHub usernames
#requestInfoUserstoExclude:

#-------------------------------------------------------------------------------
# Configuration for sentiment-bot - https://github.com/behaviorbot/sentiment-bot
# *Required* toxicity threshold between 0 and .99 with the higher numbers being the most toxic
# Anything higher than this threshold will be marked as toxic and commented on
sentimentBotToxicityThreshold: .9

# *Required* Comment to reply with
sentimentBotReplyComment: >
  Please be sure to review the code of conduct and be respectful of other users.
