# Netlify configuration file
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
command = "bundle install; bundle exec jekyll build --drafts"
publish = "_site"


[build.environment]
SECRETS_SCAN_SMART_DETECTION_OMIT_VALUES = "AIzaSyDcmx-nLYfqvrfpEmVJuclwt9akayYfUgg"
