apiVersion: v1
entries:
  meshery:
  - apiVersion: v2
    created: "2020-10-29T09:39:56.144813645+08:00"
    dependencies:
    - condition: mesheryistio.enabled
      name: mesheryistio
      repository: ""
      version: 0.1.0
    - condition: mesherylinkerd.enabled
      name: mesherylinkerd
      repository: ""
      version: 0.1.0
    - condition: mesheryconsul.enabled
      name: mesheryconsul
      repository: ""
      version: 0.1.0
    description: Meshery chart for deploying Meshery and Meshery's adapters.
    digest: bdeb78916694c5ef2a24c62cfc83b1789b29ce7b335bcf431b3975eb90072aee
    icon: https://github.com/layer5io/meshery/blob/master/ui/public/static/img/meshery-logo/meshery-logo.svg
    keywords:
    - meshery
    - mesheryistio
    - mesherylinkerd
    - mesheryconsul
    maintainers:
    - email: urakiny@gmail.com
      name: aisuko
    - email: lee.calcote@layer5.io
      name: Lee Calcote         
    - email: community@layer5.io
      name: Layer5 Authors
    name: meshery
    type: application
    urls:
    - meshery-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: latest
    created: "2020-10-29T09:39:56.143195851+08:00"
    dependencies:
    - condition: mesheryistio.enabled
      name: mesheryistio
      repository: ""
      version: 0.1.0
    - condition: mesherylinkerd.enabled
      name: mesherylinkerd
      repository: ""
      version: 0.1.0
    description: Meshery chart for deploying Meshery and Meshery's adapters.
    digest: 65fa90d72355425b85c0299a711b652afb6e7f8f8b856b3c939883f049f60740
    icon: https://github.com/layer5io/meshery/blob/master/ui/static/img/meshery-logo/meshery-logo.svg
    keywords:
    - meshery
    - mesheryistio
    - mesherylinkerd
    maintainers:
    - email: urakiny@gmail.com
      name: aisuko
    - email: lee.calcote@layer5.io
      name: Lee Calcote         
    - email: community@layer5.io
      name: Layer5 Authors   
    name: meshery
    type: application
    urls:
    - meshery-0.1.0.tgz
    version: 0.1.0
generated: "2020-10-29T09:39:56.135601802+08:00"
