name: Update Cloud Native Catalog
on:
  repository_dispatch:
    types: [update_catalog]
jobs:
  UpdateCloudNativeCatalog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set env
        run : |
          echo "MESHERY_CLOUD_BASE_URL=http://meshery.layer5.io" >> $GITHUB_ENV
          echo "MESHERY_CATALOG_FILES_DIR=catalog" >> $GITHUB_ENV
      - name: Update Catalog Patterns
        run: |
          catalogPatterns=$(curl -sS "$MESHERY_CLOUD_BASE_URL/patterns/catalog" 2>./err.txt)
          if [[ "$(<err.txt)" != "" ]]; then
            >&2 echo "Error connecting to Meshery Cloud"
            >&2 echo "$(<err.txt)"
          fi
          echo $catalogPatterns > temp.json
          patternCount=$(jq length temp.json)
          if [[ "$patternCount" == "" ]]; then
            patternCount=0
          fi

          echo "Found $patternCount catalog patterns"

          for (( idx=0; idx<$patternCount; idx++ ))
          do
            filename=$(jq -r .[$idx].id temp.json)
            patternInfo="$(jq -r .[$idx].catalog_data.pattern_info temp.json)"
            patternCaveats="$(jq -r .[$idx].catalog_data.pattern_caveats temp.json)"
            patternType="$(jq -r .[$idx].catalog_data.type temp.json)"
            patternName="$(jq -r .[$idx].name temp.json)"
            markdownName="$(echo "$patternName" | tr ' ' '-' | tr '[:upper:]' '[:lower:]')"
            compatibility=""

            if [[ $patternInfo == "null" ]]; then
              patternInfo="\"\""
            fi

            if [[ $patternCaveats == "null" ]]; then
              patternCaveats="\"\""
            fi

            if [[ $patternType == "null" ]]; then
              patternType="Deployment"
            fi

            compatLength=$(jq -r ".[$idx].catalog_data.compatibility | length" temp.json)

            for (( compatIdx=0; compatIdx<$compatLength; compatIdx++ ))
            do
              compatibility+="\n"
              compatibility+="    - $(jq -r ".[$idx].catalog_data.compatibility[$compatIdx]" temp.json)"
            done

            patternFile="$(jq -r .[$idx].pattern_file temp.json)"
            echo "$patternFile" > $MESHERY_CATALOG_FILES_DIR/$filename.yaml

            echo "---
          layout: item
          name: $patternName
          type: $patternType
          compatibility: $compatibility
          patternId: $(printf "MESHERY%03d" $idx)
          image: /images/patterns/service-mesh.svg
          patternInfo: $patternInfo
          patternCaveats: $patternCaveats
          URL: 'https://raw.githubusercontent.com/meshery/meshery.io/master/$MESHERY_CATALOG_FILES_DIR/$filename.yaml'
          downloadLink: $filename.yaml
          ---" > ./collections/_catalog/"$(echo $patternType | tr '[:upper:]' '[:lower:]')"/$markdownName.md
          done
          rm temp.json
          rm err.txt
      - name: Update Catalog Filters
        run: |
          catalogFilters=$(curl -sS "$MESHERY_CLOUD_BASE_URL/filters/catalog" 2>./err.txt)
          if [[ "$(<err.txt)" != "" ]]; then
            >&2 echo "Error connecting to Meshery Cloud"
            >&2 echo "$(<err.txt)"
          fi

          echo $catalogFilters > temp.json
          filterCount=$(jq length temp.json)
          if [[ "$filterCount" == "" ]]; then
            filterCount=0
          fi

          echo "Found $filterCount catalog filters"

          for (( idx=0; idx<$filterCount; idx++ ))
          do
            filename=$(jq -r .[$idx].id temp.json)
            filterInfo="$(jq -r .[$idx].catalog_data.filter_info temp.json)"
            filterCaveats="$(jq -r .[$idx].catalog_data.filter_caveats temp.json)"
            filterType="$(jq -r .[$idx].catalog_data.type temp.json)"
            filterName="$(jq -r .[$idx].name temp.json)"
            markdownName="$(echo "$filterName" | tr ' ' '-' | tr '[:upper:]' '[:lower:]')"
            compatibility=""

            if [[ $filterInfo == "null" ]]; then
              filterInfo="\"\""
            fi

            if [[ $filterCaveats == "null" ]]; then
              filterCaveats="\"\""
            fi

            if [[ $filterType == "null" ]]; then
              patternType="wasm filter"
            fi

            compatLength=$(jq -r ".[$idx].catalog_data.compatibility | length" temp.json)

            for (( compatIdx=0; compatIdx<$compatLength; compatIdx++ ))
            do
              compatibility+="\n"
              compatibility+="    - $(jq -r ".[$idx].catalog_data.compatibility[$compatIdx]" temp.json)"
            done

            filterFile="$(jq -r .[$idx].filter_file temp.json)"
            echo "$filterFile" > $MESHERY_CATALOG_FILES_DIR/$filename.yaml

            echo "---
          layout: item
          name: $filterName
          type: $filterType
          compatibility: $compatibility
          patternId: $(printf "FILTER%03d" $idx)
          image: /images/webassembly_logo.svg
          filterInfo: $filterInfo
          filterCaveats: $filterCaveats
          URL: 'https://raw.githubusercontent.com/meshery/meshery.io/master/$MESHERY_CATALOG_FILES_DIR/$filename.yaml'
          downloadLink: $filename.yaml
          ---" > ./collections/_catalog/"$(echo $filterType | tr '[:upper:]' '[:lower:]')"/$markdownName.md
          done
          rm temp.json
          rm err.txt
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: docs
          commit_user_name: l5io
          commit_user_email: ci@layer5.io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: '--signoff'
          commit_message: '[Catalog] Update Catalog items'

